stages: # List of stages for jobs, and their order of execution
  - check
  - publish-docs
  - publish-web

check-web:
  image: node:20
  stage: check
  needs: []
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y
      --no-install-recommends git-lfs ffmpeg wget build-essential checkinstall
      libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev
      libbz2-dev libffi-dev sqlite3 zlib1g-dev

    - wget https://www.python.org/ftp/python/3.12.2/Python-3.12.2.tar.xz -O
      /tmp/python.tar.xz && tar -xf /tmp/python.tar.xz -C /tmp && cd
      /tmp/Python-3.12.2 && ./configure --enable-optimizations
      --prefix=$HOME/.local && make -j $(nproc) && make install && cd && rm -r
      /tmp/Python-3.12.2 && rm /tmp/python.tar.xz

    - export PATH=$HOME/.local/bin:$PATH

    - pip3 install -U pip setuptools
    - pip3 install fuzzysearch
    - pip3 install torch==2.2.1+cpu torchaudio==2.2.1+cpu --index-url
      https://download.pytorch.org/whl/cpu
    - pip3 install git+https://github.com/m-bain/whisperx.git

    - export PYTHONPATH=$(eval "python3 -c \"import sys; print(':'.join([p for p
      in sys.path if p]))\"")

    - yarn
    - yarn check
    - yarn test

pages:
  image: node:18-alpine
  stage: publish-docs
  needs:
    - check-web
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - yarn workspaces focus @storyteller/docs
    - yarn build:docs
  artifacts:
    paths:
      - public

publish-web:
  image: docker:20.10.16
  stage: publish-web
  needs:
    - check-web
  rules:
    - if: $CI_COMMIT_BRANCH == "al-js"
  services:
    - name: docker:20.10.16-dind
      alias: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker context create gitlab-ci
    - docker buildx create --use --driver=docker-container gitlab-ci
  script:
    - docker buildx build --push -f docker/web.Dockerfile --cache-from
      type=registry,ref=$CI_REGISTRY_IMAGE:next --cache-to
      type=registry,ref=$CI_REGISTRY_IMAGE:next,mode=max --tag
      $CI_REGISTRY_IMAGE:next .
