
stages: # List of stages for jobs, and their order of execution
  - publish

publish-api:
  image: docker:dind
  stage: publish
  services:
    - docker:dind
  variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/api:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE/api:latest --tag $CI_REGISTRY_IMAGE/api:latest .
    - docker push $CI_REGISTRY_IMAGE/api:latest

publish-web:
  image: docker:dind
  stage: publish
  services:
    - docker:dind
  variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/web:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE/web:latest --tag $CI_REGISTRY_IMAGE/web:latest .
    - docker push $CI_REGISTRY_IMAGE/web:latest
