stages: # List of stages for jobs, and their order of execution
  - check
  - publish-docs
  - publish-web

check-web:
  image: registry.gitlab.com/smoores/storyteller-base:latest
  stage: check
  needs: []
  script:
    - yarn
    - yarn check
    - yarn test

pages:
  image: node:18-alpine
  stage: publish-docs
  needs:
    - check-web
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - yarn workspaces focus @storyteller/docs
    - yarn build:docs
  artifacts:
    paths:
      - public

publish-web:
  image: docker:20.10.16
  stage: publish-web
  needs:
    - check-web
  rules:
    - if: $CI_COMMIT_BRANCH == "all-js"
  services:
    - name: docker:20.10.16-dind
      alias: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker context create gitlab-ci
    - docker buildx create --use --driver=docker-container gitlab-ci
  script:
    - docker buildx build --push -f docker/web.Dockerfile --cache-from
      type=registry,ref=$CI_REGISTRY_IMAGE/cache:next --cache-to
      type=registry,ref=$CI_REGISTRY_IMAGE/cache:next,mode=max --tag
      $CI_REGISTRY_IMAGE:next --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .

publish-cuda:
  image: docker:20.10.16
  stage: publish-web
  needs:
    - check-web
  rules:
    - if: $CI_COMMIT_BRANCH == "all-js"
  services:
    - name: docker:20.10.16-dind
      alias: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker context create gitlab-ci
    - docker buildx create --use --driver=docker-container gitlab-ci
  script:
    - docker buildx build --push -f docker/web.Dockerfile --cache-from
      type=registry,ref=$CI_REGISTRY_IMAGE/cache:cuda-next --cache-to
      type=registry,ref=$CI_REGISTRY_IMAGE/cache:cuda-next,mode=max --tag
      $CI_REGISTRY_IMAGE:cuda-next --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      .
