stages: # List of stages for jobs, and their order of execution
  - publish

publish-api:
  image: docker:stable
  stage: publish
  services:
    - docker:stable-dind
  variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # - docker pull $CI_REGISTRY_IMAGE/api:latest || true
    - docker build -f Dockerfile.api --cache-from $CI_REGISTRY_IMAGE/api:latest --tag $CI_REGISTRY_IMAGE/api:latest --build-arg BUILDKIT_INLINE_CACHE=1 .
    - docker push $CI_REGISTRY_IMAGE/api:latest

publish-web:
  image: docker:stable
  stage: publish
  services:
    - docker:stable-dind
  variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # - docker pull $CI_REGISTRY_IMAGE/web:latest || true
    - docker build -f Dockerfile.web --cache-from $CI_REGISTRY_IMAGE/web:latest --tag $CI_REGISTRY_IMAGE/web:latest --build-arg BUILDKIT_INLINE_CACHE=1 storyteller/web
    - docker push $CI_REGISTRY_IMAGE/web:latest
