stages: # List of stages for jobs, and their order of execution
  - publish

publish-api:
  image: docker:dind
  stage: publish
  services:
    - docker:dind
  variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use --driver=docker-container
  script:
    - docker buildx build --push -f Dockerfile.api --cache-from type=registry,ref=$CI_REGISTRY_IMAGE/api-cache:latest --cache-to type=registry,ref=$CI_REGISTRY_IMAGE/api-cache:latest,mode=max --tag $CI_REGISTRY_IMAGE/api:latest .

publish-web:
  image: docker:dind
  stage: publish
  services:
    - docker:dind
  variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use --driver=docker-container
  script:
    - docker buildx build --push -f Dockerfile.web --cache-from type=registry,ref=$CI_REGISTRY_IMAGE/web-cache:latest --cache-to type=registry,ref=$CI_REGISTRY_IMAGE/web-cache:latest,mode=max --tag $CI_REGISTRY_IMAGE/web:latest storyteller/web
