stages: # List of stages for jobs, and their order of execution
  - publish-docs
  - publish-api
  - publish-web

pages:
  image: node:18-alpine
  stage: publish-docs
  needs: []
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - cd docs
    - yarn
    - yarn build
  artifacts:
    paths:
      - public

publish-api:
  image: docker:20.10.16
  stage: publish-api
  needs: []
  rules:
    - if: $CI_COMMIT_BRANCH == "cuda"
  services:
    - name: docker:20.10.16-dind
      alias: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker context create gitlab-ci
    - docker buildx create --use --driver=docker-container gitlab-ci
  script:
    - docker buildx build --push -f Dockerfile.api --cache-from type=registry,ref=$CI_REGISTRY_IMAGE/api-cache:cuda --cache-to type=registry,ref=$CI_REGISTRY_IMAGE/api-cache:cuda,mode=max --tag $CI_REGISTRY_IMAGE/api:cuda .

publish-web:
  image: docker:20.10.16
  stage: publish-web
  needs: []
  rules:
    - if: $CI_COMMIT_BRANCH == "cuda"
  services:
    - name: docker:20.10.16-dind
      alias: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker context create gitlab-ci
    - docker buildx create --use --driver=docker-container gitlab-ci
  script:
    - docker buildx build --push -f Dockerfile.web --cache-from type=registry,ref=$CI_REGISTRY_IMAGE/web-cache:cuda --cache-to type=registry,ref=$CI_REGISTRY_IMAGE/web-cache:cuda,mode=max --tag $CI_REGISTRY_IMAGE/web:cuda web
