changesetIgnorePatterns:
  - "**/*.test.{js,ts,jsx,tsx}"
  - "**/__fixtures/**/*"
  - package.json
  - "**/tsconfig.json"
  - "**/README.md"
  - "**/.gitignore"
  - "**/.yarnrc.yml"
  - .devcontainer/*
  - .vscode/*
  - .husky/*
  - .yarn/*

nodeLinker: node-modules

preferDeferredVersions: true

yarnPath: .yarn/releases/yarn-4.5.3.cjs
