# Example compose config for Storyteller

services:
  api:
    # Swap in the commented out image line below to enable CUDA
    # image: registry.gitlab.com/smoores/storyteller/api:cuda
    image: registry.gitlab.com/smoores/storyteller/api:latest
    # Uncomment for CUDA
    # runtime: nvidia
    volumes:
      # This can be whatever you like; you can even use a
      # named volume rather than a bind mount, though it's easier
      # to inspect the files with a mount.
      # If you're running on macOS or Windows, you may want to
      # consider using a named volume, which will considerably
      # improve performance.
      - ~/Documents/Storyteller:/data:rw
    # environment:
      # Uncomment for CUDA
      # - STORYTELLER_DEVICE=cuda
      # - NVIDIA_VISIBLE_DEVICES=all

  web:
    image: registry.gitlab.com/smoores/storyteller/web:latest
    environment:
      - STORYTELLER_API_HOST=http://api:8000
    ports:
      - "8001:8001"
