# Example compose config for Storyteller

services:
  web:
    image: registry.gitlab.com/smoores/storyteller:next
    # Uncomment for CUDA
    # runtime: nvidia
    volumes:
      # This can be whatever you like; you can even use a
      # named volume rather than a bind mount, though it's easier
      # to inspect the files with a mount.
      # If you're running on macOS or Windows, you may want to
      # consider using a named volume, which will considerably
      # improve performance.
      - ~/Documents/Storyteller:/data:rw
    environment:
      # Generate a cryptopgraphically secure random string,
      # e.g. with:
      #  openssl rand -base64 32
      - STORYTELLER_SECRET_KEY=<some random value>
    # Uncomment for CUDA
    # - STORYTELLER_DEVICE=cuda
    # - NVIDIA_VISIBLE_DEVICES=all

    ports:
      - "8001:8001"
