{
  # Description of what this flake provides
  description = "Development environment for Storyteller";

  # External dependencies used by this flake
  inputs = {
    # The main Nix packages collection
    nixpkgs.url = "nixpkgs";
    # devenv provides a declarative development environment
    devenv.url = "github:cachix/devenv";
  };

  # Configure Nix to use the devenv binary cache
  nixConfig = {
    extra-trusted-public-keys = "devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=";
    extra-substituters = "https://devenv.cachix.org";
  };

  # The main flake outputs
  outputs =
    {
      self,
      nixpkgs,
      devenv,
      ...
    }@inputs:
    let
      # Define which systems this flake supports
      allSystems = [
        "x86_64-linux" # 64-bit Intel/AMD Linux
        "aarch64-linux" # 64-bit ARM Linux
        "x86_64-darwin" # 64-bit Intel macOS
        "aarch64-darwin" # 64-bit ARM macOS
      ];

      # Helper function to generate system-specific attributes
      forAllSystems =
        f:
        nixpkgs.lib.genAttrs allSystems (
          system:
          f {
            pkgs = import nixpkgs { inherit system; };
          }
        );
    in
    {
      # Make devenv scripts available as flake packages
      packages = nixpkgs.lib.genAttrs allSystems (system: {
        devenv-up = self.devShells.${system}.default.config.procfileScript;
        devenv-test = self.devShells.${system}.default.config.test;
      });

      # Development shell configuration
      devShells = forAllSystems (
        { pkgs }:
        {
          default = devenv.lib.mkShell {
            inherit inputs pkgs;
            modules = [
              (
                { pkgs, config, ... }:
                {
                  # Required system packages
                  packages = [
                    pkgs.ffmpeg # For audio processing
                    pkgs.nodejs_22 # Node.js runtime
                    (pkgs.yarn.override { nodejs = pkgs.nodejs_22; }) # Yarn package manager
                    pkgs.sqlite # SQLite database
                    pkgs.git-lfs # Git Large File Storage
                  ];

                  # Task to initialize the development environment
                  tasks."repo:init" = {
                    description = "Do necessary work for setting up development";
                    exec = ''
                      yarn install
                      git lfs pull
                      touch .devenv-initialized'';
                    status = "test -f .devenv-initialized";
                    before = [ "devenv:enterShell" "devenv:enterTest" ];
                  };

                  # VS Code devcontainer configuration
                  devcontainer.enable = true;
                  devcontainer.settings._COMMENT1 = "This file is auto-generated by flake.nix";
                  devcontainer.settings._COMMENT2 = "It gets overwritten by nix develop and the devcontainer.";
                  # Required VS Code extensions
                  devcontainer.settings.customizations.vscode.extensions = [
                    # Default; needed to make devenv devcontainer work
                    "mkhl.direnv"
                    # Copied from .vscode/extensions.json
                    "arcanis.vscode-zipfs"
                    "dbaeumer.vscode-eslint"
                    "esbenp.prettier-vscode"
                    "ms-python.python"
                    "ms-python.vscode-pylance"
                    "ms-azuretools.vscode-docker"
                    "ms-python.black-formatter"
                    "bbenoist.nix"
                    "gitlab.gitlab-workflow"
                    "redhat.vscode-yaml"
                  ];
                  # Setup command for devcontainer
                  devcontainer.settings.updateContentCommand = ''
                    mkdir -p ~/.local/share/nix/
                    echo -n '{"extra-substituters":{"https://devenv.cachix.org":true},"extra-trusted-public-keys":{"devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=":true}}' > ~/.local/share/nix/trusted-settings.json
                    DIRENV_WARN_TIMEOUT=0 direnv exec ''${containerWorkspaceFolder} devenv test'';

                  # Test command to verify environment
                  enterTest = "yarn check";

                  # Commented out process definition
                  # processes.run.exec = "hello";
                }
              )
            ];
            # Commented out library path setting
            # LD_LIBRARY_PATH = "${libstdcpp}/lib/";
          };
        }
      );
    };
}
