# packageExtensions:
#   axios@*:
#     dependencies:
#       debug: "*"
#   debug@*:
#     dependencies:
#       supports-color: "^8.0.0"

supportedArchitectures:
  os:
    - darwin
    - linux
  cpu:
    - arm64
    - x64
  libc:
    - glibc
    - musl
